spring.application.name=projetoS_TM

spring.jpa.hibernate.ddl-auto = update

spring.datasource.url=jdbc:mysql://localhost:3306/TrezeMaio_DB?createDatabaseIfNotExist=true&connectionCollation=utf8mb4_bin

spring.datasource.username=root

spring.datasource.password=
